### ISSUE TITLE
Termux : failed to find libmagic

### ISSUE THREAD

**Issue by rounakdatta** [yask123/Instant-Music-Downloader#124]
Termux is installed on an Android device along with Python 3.6.3 
**pip install instantmusic** does not return any error

_**instantmusic**
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instantmusic", line 8, in <module>
    import eyed3
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eyed3/__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/eyed3/utils/__init__.py", line 27, in <module>
    import magic
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/magic.py", line 176, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation_

Please help me resolving this error. I wanted to package this script into an Android app with the author's permission.

**Comment by ololoch** [comment]
hello. 
just run "pkg install sox".
hope it helps

**Comment by rounakdatta** [comment]
oh just wow!
it worked.
thanks a ton!

**Comment by mr-antisecurity** [comment]
> hello.
> just run "pkg install sox".
> hope it helps

Hey bro, I had the same issue but when I try to run "pkg install sox" it gives error "unable to locate sox"
