### ISSUE TITLE
Crash when printing unicode results

### ISSUE THREAD

**Issue by sergiocorreia** [yask123/Instant-Music-Downloader#30]
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\Scripts\instantmusic.py", line 36, in <module>
    print("Found: " + title)
  File "c:\program files (x86)\python 3.5\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position 35: character maps to <undefined>
```

A quick soln would be to add `import sys` and then replace the print line with:

`print("Found: " + title.encode('utf8').decode(sys.stdout.encoding))`

This should allow nice results on *nix and garbled but at least working results on windows

**Comment by pickfire** [comment]
It didn't crash in my computer and instead it didn't display the unicode characters:
```
Enter songname/lyrics/artist or other
> 今天我
Searching...
Found: [0] b'\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe9\x9d\x9e\xe5\xb8\xb8\xe5\xaf\x82\xe5\xaf\x9e'
[1] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 2'
[2] b'\xe9\x92\x9f\xe9\x95\x87\xe6\xb6\x9b-\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe9\x9d\x9e\xe5\xb8\xb8\xe5\xaf\x82\xe5\xaf\x9e.flv'
[3] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 1'
[4] b'\xe3\x80\x90\xe4\xb8\xad\xe5\xad\x97\xe3\x80\x91\xe6\x9c\xb4\xe6\x9c\x89\xe5\xa4\xa9 \xe7\x9c\x8b\xe8\xa6\x8b\xe5\x91\xb3\xe9\x81\x93\xe7\x9a\x84\xe5\xb0\x91\xe5\xa5\xb3OST "\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe4\xb9\x9f(\xeb\x82\x9c \xec\x98\xa4\xeb\x8a\x98\xeb\x8f\x84)" MV'
[5] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 7'
[6] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xef\xbc\x8c\xe6\x88\x91\xe6\x8a\x8a\xe5\xaa\xbd\xe5\xaa\xbdunfriend\xe4\xba\x86\xe3\x80\x8b'
[7] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 8'
[8] b'20140207 \xe4\xb8\xad\xe5\x9b\xbd\xe5\xa5\xbd\xe6\xad\x8c\xe6\x9b\xb2 \xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe7\x96\xaf\xe4\xba\x86\xe3\x80\x8b 43\xe5\xb2\x81\xe8\x80\x81\xe9\x92\xb1\xe7\xa7\x80\xe6\x96\xb9\xe8\xa8\x80\xe8\x93\x9d\xe8\xb0\x83 \xe5\x88\x98\xe6\xac\xa2\xe9\xa3\x99\xe8\xa5\xbf\xe5\xae\x89\xe8\xaf\x9d\xe5\x8a\x9b\xe6\x8c\xba\xef\xbc\x88\xe5\x91\xa8\xe5\x8d\x8e\xe5\x81\xa5\xe7\xbb\x84\xef\xbc\x89'
[9] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 3'
[10] b'\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe7\x94\x9f\xe6\x97\xa5\xe5\x94\xb7!'
[11] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 10'
[12] b'\xe7\xbb\x8f\xe5\x85\xb8\xe8\x80\x81\xe7\x94\xb5\xe5\xbd\xb1\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe4\xbc\x91\xe6\x81\xaf\xe3\x80\x8bClassical Chinese Movie: A Day of A Policeman'
[13] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 12'
[14] b'20151010\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x9c\x80\xe7\xbe\x8e'
[15] b'\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe7\x94\x9f\xe6\x97\xa5\xe5\x94\xb7! \xe5\xad\x97\xe5\xb9\x95\xe7\x89\x88'
[16] b'\xe5\x9b\xbd\xe4\xba\xa7\xe7\xbb\x8f\xe5\x85\xb8\xe9\xbb\x91\xe7\x99\xbd\xe8\x80\x81\xe7\x94\xb5\xe5\xbd\xb1\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe4\xbc\x91\xe6\x81\xaf\xe3\x80\x8b 1959\xe5\xb9\xb4'
[17] b'\xe3\x80\x8a\xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe6\x98\xaf\xe8\xb0\x81?\xe3\x80\x8bBUSYBODY - Episode 13'
[18] b'04. \xe6\x9c\xb1\xe5\x92\xaa\xe5\x92\xaa - \xe4\xbb\x8a\xe5\xa4\xa9\xe7\x9a\x84\xe6\x88\x91'
[19] b'\xe9\x8d\xbe\xe9\x8e\xae\xe6\xbf\xa4 - \xe4\xbb\x8a\xe5\xa4\xa9\xe6\x88\x91\xe9\x9d\x9e\xe5\xb8\xb8\xe5\xaf\x82\xe5\xaf\x9e (1987)'
Pick one:
```

**Comment by luzpaz** [comment]
is it possible to also represent RTL languages correctly?

**Comment by yask123** [comment]
Ah, It worked fine in my terminal 
```
Enter songname/lyrics/artist or other
> 今天我
Searching...
Found: [0] 今天我非常寂寞
[1] 钟镇涛-今天我非常寂寞.flv
[2] 【中字】朴有天 看見味道的少女OST "今天我也(난 오늘도)" MV
[3] 《今天我是谁?》BUSYBODY - Episode 1
[4] 《今天，我把媽媽unfriend了》
[5] 《今天我是谁?》BUSYBODY - Episode 7
[6] 《今天我是谁?》BUSYBODY - Episode 2
[7] 20140207 中国好歌曲 《今天我疯了》 43岁老钱秀方言蓝调 刘欢飙西安话力挺（周华健组）
[8] 今天我生日唷!
[9] 经典老电影《今天我休息》Classical Chinese Movie: A Day of A Policeman
[10] 《今天我是谁?》BUSYBODY - Episode 8
[11] 《今天我是谁?》BUSYBODY - Episode 3
[12] 《今天我相亲》
[13] 《今天我是谁?》BUSYBODY - Episode 10
[14] 国产经典黑白老电影《今天我休息》 1959年
[15] 20151010今天我最美
[16] 《今天我是谁?》BUSYBODY - Episode 12
[17] 今天我最美走光特輯
[18] 04. 朱咪咪 - 今天的我
[19] 今天我相亲 奋斗男遇上"富二代"
Pick one:
```
Maybe its related to terminal fonts?
I am using `iterm2 ` on OSX.

**Comment by luzpaz** [comment]
```
Enter songname/lyrics/artist or other
> beri sacharoff
Searching...
Found: [0] Israeli musician Beri Sacharoff @ IDC Radio
[1] Daniel Zamir Jazz Concert - Johannesburg, South Africa
[2] IDC International Radio
[3] האירוחים החמים
[4] ברי סחרוף - היום יום הולדת - לרדיו הבינתחומי
[5] ברי סחרוף - חבל שאת לא
[6] radio sound music
[7] Infected Mushroom & Berry saharof Birthday
[8] TV Buddha's live @ IDC Radio
[9] Radio kol israel, Israel quiz music contest
[10] דייויד ברוזה @ הרדיו הבינתחומי
[11] הרדיו הבינתחומי @  loshabibos
[12] IDC Radio's Chain Show - Ninet Tayeb and Alon Levi
[13] J.viewz wish IDC Radio a happy B-day
[14] JEWISH - INTRODUCING RADIO SHALOM - Global & local multilingual Jewish radio 24/6
[15] תכנית שרשרת - אניה בוקשטיין ואושרי כהן @ הרדיו הבינתחומי
[16] תכנית שרשרת - אלון לוי ויובל שרף @ הרדיו הבינתחומי
[17] תכנית שרשרת - יובל שרף ואניה בוקשטיין @ הרדיו הבינתחומי
[18] Uzi Navon live @ IDC Radio
[19] תכנית שרשרת - עברי לידר ונינט טייב @ הרדיו הבינתחומי
```
I'm also using iterm2. What's odd is that in the terminal it's backwards... pasted in to github it re-arranges correctly. so it's prob. an issue on my end. <shrug>

**Comment by luzpaz** [comment]
See screenshot for comparison: 
![screenshot 2015-10-10 13 58 04](https://cloud.githubusercontent.com/assets/4140247/10412803/f894a5a2-6f56-11e5-9aa8-9dc3b2938045.png)

**Comment by pickfire** [comment]
I am using [`st`](st.suckless.org), I can print normal chinese character but I can't use it there. I am still not sure what causes it.
