### ISSUE TITLE
TypeError: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by hut8** [yask123/Instant-Music-Downloader#70]
```
Traceback (most recent call last):
  File "/usr/local/bin/instantmusic", line 277, in <module>
    main()
  File "/usr/local/bin/instantmusic", line 274, in main
    print('Downloaded: %s' % ', '.join(downloads))
```

In a bunch of places you use the `content` field of the response from `requests.get()`, when you should be using the `text` since you're dealing with HTML, which has an encoding. I'm pretty sure that if you change all of those, except if you are actually dealing with binary content (I haven't looked yet), then you can fix this.

I'll put in a PR tonight if I get a chance.

**Comment by bobjackjohnson** [comment]
I'm new to all of this open source contributing stuff. I fixed the error on my system but I have no idea how to go about sharing it.

I replaced "print('Downloaded: %s' % ', '.join(downloads))"
with "print('Downloaded: %s' % ', '.join(str(v) for v in downloads))"
