### ISSUE TITLE
Issue installing on mac 10.11.1

### ISSUE THREAD

**Issue by sdubrul** [yask123/Instant-Music-Downloader#83]
I got the following issue installing the package from PyPi:

mac:~ Huomenta$ pip search instantmusic
instantmusic     - Instantly download any song! Without knowing the name of
                   the song!!!!
mac:~ Huomenta$ sudo pip install instantmusic
The directory '/Users/Huomenta/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Huomenta/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting instantmusic
  Downloading instantmusic-2.2.tar.gz
Collecting youtube-dl (from instantmusic)
  Downloading youtube_dl-2015.11.02-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 102kB/s 
Collecting BeautifulSoup4 (from instantmusic)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 109kB/s 
Collecting eyed3 (from instantmusic)
  Downloading eyeD3-0.7.8.tar.gz (226kB)
    100% |████████████████████████████████| 229kB 123kB/s 
Collecting requests (from instantmusic)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 93kB/s 
Installing collected packages: youtube-dl, BeautifulSoup4, eyed3, requests, instantmusic
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/wheel.py", line 371, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 71, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/etc'
mac:~ Huomenta$

**Comment by yask123** [comment]
run `sudo pip install instantmusic`
